### ISSUE TITLE
Repo says "sane language", but Go chosen

### ISSUE THREAD

**Issue by LeftyBC** [gr4y/fitbit-graphite#1]
... just kidding!

I found this repo while looking for exactly the same thing, and was about to be all disappointed that there was only one commit, but then I saw that it was only a couple of hours old ;)

**Comment by gr4y** [comment]
I am currently working on an replacement for github.com/gr4y/fitbit-graphite.rb in go. The main problem I currently faced is that dev.fitbit.com is kinda borked. I can't create new apps, so I have to wait until FitBit fixed that. :grinning:
