### ISSUE TITLE
Unable to setup access to API

### ISSUE THREAD

**Issue by roflmao** [gr4y/fitbit-graphite#1]
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: unauthorized_client - A "Personal" application is only authorized to request access tokens from the owner of the application. 

```
https://fitbit.com/oauth2/authorize?access_type=online&client_id=XXXXX&response_type=code&scope=activity+heartrate+location+nutrition+profile+settings+sleep+social+weight&state=XXxxxxXXxxxxxxxxlongstringhere
```

**Comment by gr4y** [comment]
I am sorry, but this project is still not ready for daily use. In fact it doesn't send data to graphite, yet. I kinda lost motivation to finally get this all done, when I read on the FitBit Dev Forums that they postponed the switch to OAuth 2.0 until August 2016. I will assign this issue to me and maybe I will continue my work on this project this weekend. I don't know if you can setup the OAuth 1.0a Access to the API with https://github.com/gr4y/fitbit-graphite.rb, after they disabled some parts of the OAuth 1.0a workflow, but on my server it still fetches my step data fine.

**Comment by roflmao** [comment]
dev.fitbit.com doesnt seem to allow creation of OAuth 1.0a keys anymore. Creating a new application gives me OAuth2.0 credentials, which didnt work putting into .settings.json:

```
/var/lib/gems/1.9.1/gems/oauth-0.5.1/lib/oauth/consumer.rb:217:in `token_request': 401 Unauthorized (OAuth::Unauthorized)
    from /var/lib/gems/1.9.1/gems/oauth-0.5.1/lib/oauth/consumer.rb:136:in `get_request_token'
    from /var/lib/gems/1.9.1/gems/fitgem-0.10.0/lib/fitgem/client.rb:167:in `request_token'
    from /root/git/fitbit-graphite.rb/lib/fitbit/graphite/base_processor.rb:31:in `authenticate!'
    from /root/git/fitbit-graphite.rb/lib/fitbit/graphite/base_processor.rb:19:in `initialize'
    from bin/fitbit-graphite:37:in `new'
    from bin/fitbit-graphite:37:in `block in <main>'
    from bin/fitbit-graphite:34:in `each'
    from bin/fitbit-graphite:34:in `<main>'
```

Thanks for the feedback!

**Comment by gr4y** [comment]
Just to keep you up to date: I started to work on it yesterday, but I noticed while reading my own code that I have to fix some more things before I release a first version, so it will take until next week, if all goes well and my ability to concentrate doesn't leave. :smile:

**Comment by roflmao** [comment]
Sounds great :)

**Comment by gr4y** [comment]
It took longer than I anticipated, but yesterday I fixed the last bug. You might want to give that project a spin. :grin: Don't forget to set your Data Retention Policies in your Carbon config, which cost me 2 hours of my life to notice. 😉
